import { writeFile } from "node:fs/promises";
import { basename, relative } from "node:path";
import type { CaptureManifestEntry } from "@doceomenter/shared";
import type { RenderInput } from "./types.js";

export async function renderMarkdown(input: RenderInput, outPath: string): Promise<string> {
  const md = buildMarkdown(input);
  await writeFile(outPath, md, "utf-8");
  return md;
}

function buildMarkdown(input: RenderInput): string {
  const { content, analysis, capture, assetsBasePath, runId, generatedAt } = input;
  const { concept, technical, summary, captions } = content;
  const { repo } = analysis;

  const lines: string[] = [];

  lines.push(`# ${repo.name}`);
  lines.push("");
  lines.push(`> ${summary.oneLiner}`);
  lines.push("");
  lines.push(`*Repository:* \`${repo.owner}/${repo.name}\`@\`${repo.ref}\` (${repo.commitSha.slice(0, 7)})  `);
  lines.push(`*Generated:* ${generatedAt}  `);
  lines.push(`*Run id:* \`${runId}\``);
  lines.push("");

  // TL;DR
  lines.push("## TL;DR");
  lines.push("");
  for (const b of summary.tldr) lines.push(`- ${b}`);
  lines.push("");

  // Concept
  lines.push("## Concept — what is it & why does it exist");
  lines.push("");
  lines.push("### What");
  lines.push(concept.what);
  lines.push("");
  lines.push("### Why");
  lines.push(concept.why);
  lines.push("");
  lines.push("### Audience");
  for (const a of concept.audience) lines.push(`- ${a}`);
  lines.push("");

  // Vision
  lines.push("## Vision");
  lines.push("");
  lines.push(concept.vision);
  lines.push("");

  // In motion
  const successful = capture.entries.filter((e) => e.status === "ok");
  if (successful.length > 0) {
    lines.push("## In motion");
    lines.push("");
    if (successful.length < capture.entries.length) {
      const failed = capture.entries.length - successful.length;
      lines.push(`> Partial capture: ${successful.length} of ${capture.entries.length} shots succeeded (${failed} failed or skipped).`);
      lines.push("");
    }
    for (const e of successful) {
      const captionMd =
        captions.find((c) => c.shotId === e.shotId)?.markdown ??
        ("caption" in e.shot ? e.shot.caption : "");
      lines.push(...embedAsset(e, captionMd, assetsBasePath));
      lines.push("");
    }
  }

  // Architecture (Mermaid as both image and code block)
  const archShots = successful.filter((e) => "target" in e.shot && e.shot.target === "code-architecture");
  if (archShots.length > 0) {
    lines.push("## Architecture");
    lines.push("");
    for (const e of archShots) {
      if ("diagramSpec" in e.shot && "mermaid" in e.shot.diagramSpec) {
        lines.push("```mermaid");
        lines.push(e.shot.diagramSpec.mermaid);
        lines.push("```");
        lines.push("");
      }
    }
  }

  // Technical
  lines.push("## Tech stack & key modules");
  lines.push("");
  lines.push("### Stack");
  lines.push("");
  lines.push("| Technology | Evidence |");
  lines.push("|---|---|");
  for (const s of technical.stack) {
    lines.push(`| ${escapeCell(s.technology)} | \`${escapeCell(s.evidence)}\` |`);
  }
  lines.push("");
  lines.push("### Architecture (narrative)");
  lines.push(technical.architecture);
  lines.push("");
  lines.push("### Data flow");
  lines.push(technical.dataFlow);
  lines.push("");
  lines.push("### Key modules");
  lines.push("");
  for (const m of technical.keyModules) {
    lines.push(`- **\`${m.path}\`** — ${m.role}: ${m.oneLineSummary}`);
    if (m.citations.length) {
      lines.push(`  - Citations: ${m.citations.map((c) => `\`${c}\``).join(", ")}`);
    }
  }
  lines.push("");

  // Getting started
  lines.push("## Getting started");
  lines.push("");
  lines.push("```bash");
  for (const cmd of technical.gettingStarted) lines.push(cmd);
  lines.push("```");
  lines.push("");

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    `*Generated by [DoceoMenter](https://github.com/Flyvendedk799/DoceoMenter) — run \`${runId}\` at ${generatedAt}.*`,
  );
  lines.push("");

  return lines.join("\n");
}

function embedAsset(e: CaptureManifestEntry, captionMd: string, assetsBasePath: string): string[] {
  if (!e.outputs) return [];
  const out: string[] = [];
  if (e.outputs.pngPath) {
    const relPath = `${assetsBasePath}/${basenameNorm(e.outputs.pngPath)}`;
    out.push(`![${escapeAlt(captionMd)}](${relPath})`);
  } else if (e.outputs.mp4Path || e.outputs.webmPath) {
    const v = e.outputs.mp4Path ?? e.outputs.webmPath!;
    const relV = `${assetsBasePath}/${basenameNorm(v)}`;
    if (e.outputs.posterPath) {
      const relP = `${assetsBasePath}/${basenameNorm(e.outputs.posterPath)}`;
      out.push(`[![Watch the recording](${relP})](${relV})`);
    } else {
      out.push(`[Watch the recording](${relV})`);
    }
  }
  if (captionMd) {
    out.push("");
    out.push(`*${captionMd.replace(/\n/g, " ")}*`);
  }
  return out;
}

function basenameNorm(p: string): string {
  // assetsBasePath is e.g. "./assets" or "../assets/screenshots"; we expect
  // the renderer's base path to point to a directory that already contains
  // the file, so we flatten to basename + sub-folder when applicable.
  const segments = p.split(/[/\\]/);
  // Keep last two segments to preserve "screenshots/foo.png" vs "videos/bar.mp4"
  return segments.slice(-2).join("/");
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|");
}

function escapeAlt(s: string): string {
  return s.replace(/[\[\]]/g, "");
}
